server:
  port: 8080
  servlet:
    context-path: /homeManage
spring:
  application:
    name: homeManage
  datasource:
    url: jdbc:mysql://localhost:3306/homemanage?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
          #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**